# Generated by Django 5.1.4 on 2024-12-31 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="auther",
            new_name="author",
        ),
    ]
